In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
arr=np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


In [4]:
import numpy as np
arr=np.ones((3,2),dtype=int)
print(arr)

[[1 1]
 [1 1]
 [1 1]]


In [5]:
import numpy as np
arr=np.array([2,3,4],dtype=float)
print(arr,type(arr))

[2. 3. 4.] <class 'numpy.ndarray'>


In [6]:
import numpy as np
arr=np.empty((2,2))
print(arr)

[[2.12199579e-314 7.63918485e-312]
 [7.62837357e-321 3.79442416e-321]]


In [7]:
import numpy as np
x=np.arange(0,20,2)
print(x)


[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
import numpy as np
arr=np.linspace(0,1,6)
print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]


In [9]:
np.random.random((3,3))

array([[0.19698198, 0.51829887, 0.07337705],
       [0.00534928, 0.06211398, 0.72260312],
       [0.20820737, 0.70846637, 0.57276335]])