In [1]:
import numpy as np


In [2]:
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40


In [3]:
print(arr[1,2])

7


In [4]:
np.random.seed(1)
arr=np.random.randint(10,size=5)
print(arr)
print(arr[-2])
print(arr[2])
print(arr[3])
print(arr[2:4])
print(arr[1:3])
print(arr[1:4:2])
print(arr[::-1])

[5 8 9 5 0]
5
9
5
[9 5]
[8 9]
[8 5]
[0 5 9 8 5]
