In [1]:
import numpy as np

arr = np.arange(1, 21)

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
int64


In [2]:
import numpy as np

np.random.seed(0)

arr = np.random.randint(0, 51, size=(4, 5))

print(arr)
print(arr.itemsize)
print(arr.nbytes)

[[44 47  0  3  3]
 [39  9 19 21 50]
 [36 23  6 24 24]
 [12  1 38 39 23]]
4
80


In [3]:
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)

print(arr[1, 2])
print(arr[-1])
print(arr[:, -1])

7
[ 9 10 11 12]
[ 4  8 12]


In [4]:
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)

print(arr[:2, :2])
print(arr[:, ::2])
print(arr[:, ::-1])

[[1 2]
 [5 6]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [5]:
import numpy as np

arr = np.arange(1, 13).reshape(3, 4)

view = arr[:3, :3]
view[0, 0] = 100

print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [6]:
arr = np.arange(1, 13).reshape(3, 4)

copy = arr[:3, :3].copy()
copy[0, 0] = 100

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
import numpy as np

arr = np.arange(1, 13)

a = arr.reshape((12, 1))
b = arr[:, np.newaxis]

print(a)
print(b)
print(np.array_equal(a, b))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
True


In [8]:
import numpy as np

np.random.seed(0)

a = np.random.randint(0, 10, (2, 3))
b = np.random.randint(0, 10, (2, 3))

v1 = np.vstack((a, b))
v2 = np.concatenate((a, b), axis=0)

h1 = np.hstack((a, b))
h2 = np.concatenate((a, b), axis=1)

print(v1)
print(v2)
print(np.array_equal(v1, v2))

print(h1)
print(h2)
print(np.array_equal(h1, h2))

[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]]
[[5 0 3]
 [3 7 9]
 [3 5 2]
 [4 7 6]]
True
[[5 0 3 3 5 2]
 [3 7 9 4 7 6]]
[[5 0 3 3 5 2]
 [3 7 9 4 7 6]]
True


In [9]:
import numpy as np

arr = np.arange(1, 16)

parts = np.split(arr, 3)

for part in parts:
    print(part)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [10]:
import numpy as np

arr = np.arange(1, 25).reshape(6, 4)

a = np.hsplit(arr, 2)
b = np.vsplit(arr, 2)

print(a[0])
print(a[1])

print(b[0])
print(b[1])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
