In [1]:
import numpy as np

x = np.random.randint(1, 50, 10)
print(x)

y = np.sort(x)
print(y)
print(x)

x.sort()
print(x)

[ 8 46 19 45 16 17 23  1 17 39]
[ 1  8 16 17 17 19 23 39 45 46]
[ 8 46 19 45 16 17 23  1 17 39]
[ 1  8 16 17 17 19 23 39 45 46]


In [2]:
i = np.argsort(x)
print(i)
print(x[i])
print(np.sort(x))

[0 1 2 3 4 5 6 7 8 9]
[ 1  8 16 17 17 19 23 39 45 46]
[ 1  8 16 17 17 19 23 39 45 46]


In [3]:
import numpy as np

x = np.random.randint(1, 50, (4, 6))

print(x)
print(np.sort(x, axis=1))
print(np.sort(x, axis=0))

[[21 31 21 49  9 21]
 [41 42 38 39 38 15]
 [ 8 14 36  9 47 35]
 [46 16  7  8 20 31]]
[[ 9 21 21 21 31 49]
 [15 38 38 39 41 42]
 [ 8  9 14 35 36 47]
 [ 7  8 16 20 31 46]]
[[ 8 14  7  8  9 15]
 [21 16 21  9 20 21]
 [41 31 36 39 38 31]
 [46 42 38 49 47 35]]


In [4]:
import numpy as np

x = np.random.randint(1, 100, 15)

p = np.partition(x, 4)
print(p[:4])

print(np.sort(x)[:4])

[ 6 17 26 28]
[ 6 17 26 28]


In [5]:
import numpy as np

student_names = np.array(["Asha", "Rahul", "Sneha", "Kiran", "Anu"])
scores = np.array([78, 65, 92, 55, 88])

i = np.argsort(scores)

print(student_names[i])
print(scores[i])

['Kiran' 'Rahul' 'Asha' 'Anu' 'Sneha']
[55 65 78 88 92]


In [6]:
import numpy as np

np.random.seed(0)

X = np.random.rand(10, 2)

dist_sq = np.sum((X[:, np.newaxis, :] - X[np.newaxis, :, :]) ** 2, axis=-1)

i = np.argsort(dist_sq, axis=1)

print(i[:, 1:3])

[[2 1]
 [0 5]
 [0 1]
 [6 0]
 [5 1]
 [1 4]
 [3 0]
 [2 1]
 [3 2]
 [6 0]]
